[theme]
# A dark-blue primary accent color for interactive elements
primaryColor = "#0d47a1"

# A light "white-blue" background color for the main content area
backgroundColor = "#e6f2ff"

# A lighter background color for the sidebar and other components
secondaryBackgroundColor = "#ffffff"

# A darker text color for better contrast against the light background
textColor = "#000000"
